version: '2'
services:
  bot:
    container_name: 'Agent301Bot'
    build:
      context: .
    stop_signal: SIGINT
    restart: unless-stopped
    command: "python3 main.py -a 3"
    volumes:
      - .:/app
